local helper = dofile(os.getenv("TESTS_DIRECTORY") .. "/support/agnosticdb_test_helper.lua")

describe("agnosticdb honors", function()
  before_each(function()
    helper.reset()
  end)

  it("exposes the honors entry points", function()
    assert.is_table(agnosticdb.honors)
    assert.is_function(agnosticdb.honors.capture)
    assert.is_function(agnosticdb.honors.finish_capture)
    assert.is_function(agnosticdb.honors.queue_names)
    assert.is_function(agnosticdb.honors.cancel_queue)
  end)
end)
